# -*- mode: ruby -*-
# vi: set ft=ruby :

project_name = 'expenses'
dev_domain = 'local.dev'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.network :private_network, ip: "192.168.43.10"

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  config.vm.synced_folder "../", "/home/vagrant/workspace/#{project_name}", :owner => 'vagrant', :group => 'www-data', :mount_options => ["dmode=775"]

  config.vm.hostname = "#{project_name}.#{dev_domain}"

  config.vm.provider :virtualbox do |vb|
    vb.name = project_name
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision :chef_solo do |chef|
  #  chef.cookbooks_path = ["../../chef/cookbooks","cookbooks"]
  #   chef.roles_path = "../my-recipes/roles"
  #   chef.data_bags_path = "../my-recipes/data_bags"
  #  chef.add_recipe "apache2"
  #  chef.add_recipe "mysql"
  #  chef.add_recipe "php"
    chef.add_recipe "expenses"
  #   chef.add_role "web"
  #
  #   # You may also specify custom JSON attributes:
    chef.json = { 
      :project_name => project_name, 
      :server_name => "#{project_name}.#{dev_domain}",
      'mysql' => {
        'server_root_password' => "root",
        'server_repl_password' => "root",
        'server_debian_password' => "root",
      }
    }
  end
end
